{{ $baseChartValues := index .Values "cray-service" }}
{{ $crayServiceValues := dict "Values" $baseChartValues "Chart" .Chart "Release" .Release}}
apiVersion: v1
kind: Service
metadata:
  name: cray-tftp
  labels:
    app.kubernetes.io/name: {{ include "cray-service.name" $crayServiceValues }}
    app.kubernetes.io/instance: {{ include "cray-service.name" $crayServiceValues }}
  annotations:
    metallb.universe.tf/address-pool: node-management
    cray.io/service: cray-tftp
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
{{- if .Values.nmn_internal_lb_supports_static_ip }}
  loadBalancerIP: {{ .Values.nmn_tftp_service_ip }}
{{- else }}
  externalIPs:
  - {{ .Values.nmn_tftp_service_ip }}
{{- end }}
  ports:
      - port: 69
        name: tftp-port
        protocol: UDP
        targetPort: 69
  selector:
    app.kubernetes.io/name: {{ include "cray-service.name" $crayServiceValues }}
    app.kubernetes.io/instance: {{ include "cray-service.name" $crayServiceValues }}
